routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProdukController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\UserController;
use App\Models\User;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', [ProdukController::class, 'dataProduk']);


Route::prefix('admin')->namespace('Admin')->group(static function () {
        Route::resource('produk', 'ProductController');
        Route::resource('user', 'UserController');
});

Route::get('/delete/{id}', [UserController::class, 'destroy'])->name('userDelete');
Route::get('/delete/[id]', [ProductController::class, 'delete'])->name('delete');

// Route::get('user', [UserController::class, 'user']);
Route::get('formproduk', 'HomeController@formproduk')->name('formproduk');
Route::get('daftarbarang', [ProdukController::class, 'daftarBarang'])->name('daftarBarang');

// Route::get('depan',[ProdukController::class,'dataProduk']);
Route::POST('formproduk', [ProdukController::class, 'store']);

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

// Route::prefix('user')->group(function () {
//     Route::resource('produk', 'ProdukController');
// });

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Produk;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $produk['produks'] = Produk::all();
        return view('backand.product.index', $produk);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backand.product.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'image' => 'image|mimes:jpeg,png,jpg,gif,svg|max:2048',
        ]);

        //$data = $request->all();


        //$data['imageName'] = $request->file('imageName')->store('img', 'public');

        //Produk::create($data);


        // dd($prouduct);


        $produks = new Produk;
        $produks->jenis = $request->jenis;
        $produks->type = $request->type;
        $produks->hight = $request->hight;
        $produks->wight = $request->wight;
        $produks->gender = $request->gender;
        $produks->hargaBeli = $request->hargaBeli;
        $produks->hargaJual = $request->hargaJual;
        $produks->status = $request->status;

        if ($request->file('imageName')) {
            $file = $request->file('imageName');
            $filename = date('YmdHi') . $file->getClientOriginalName();
            $file->move(public_path('uploads'), $filename);
            $produks['imageName'] = $filename;
        }
        //dd($produks);

        $produks->save();
        return back()->with('success', 'Data berhasil dibuat');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $produks = Produk::findOrFail($id);
        return view('backand.product.show', compact([
            'produks'
        ]));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $produks = Produk::findOrFail($id);
        return view('backand.product.update', compact([
            'produks'
        ]));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        //  $data = $request->all();
        //  $data['imageName'] = $request->file('imageName')->store('img','public');

        // Produk::create($data); 
        $produks = Produk::findOrFail($id);
        $produks->jenis = $request->jenis;
        $produks->type = $request->type;
        $produks->hight = $request->hight;
        $produks->wight = $request->wight;
        $produks->gender = $request->gender;
        $produks->hargaJual = $request->hargaJual;
        $produks->hargaBeli = $request->hargaBeli;
        $produks->status = $request->status;
        // dd($produks);

        $produks->save();
        return back()->with('success', 'Data berhasil diupdate');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function delete($id)
    {
        $produk = Produk::find($id);
        $produk->delete();
        return redirect()->route('produk.index')->with('success', 'Data berhasil di hapus');
    }
}

resources/views/backand/product/create.blade.php
@extends('layouts.master')

@section('title')
    RSUD Anugrah Sehat Afiat
@endsection

@section('title-content')
    Farm
@endsection

@section('content')
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <div class="container">
        <div class="col-md-12">
            <div class="row justify-content-center">
                <div class="col-md-12">
                    <h1 class="h1 pb-4 py-3">Buat Data Pasien</h1>
                    <div class="card mt-2">
                        <div class="card-header">{{ __('Data Pasien') }}</div>
                        <div class="card-body">
                            @if ($message = Session::get('success'))
                                <div class="alert alert-success alert-block">
                                    <button type="button" class="close" data-dismiss="alert">×</button>
                                    <strong>{{ $message }}</strong>
                                </div>
                            @endif
                            @if (count($errors) > 0)
                                <div class="alert alert-danger">
                                    <strong>Whoops!</strong> There were some problems with your input.
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif
                            <form action="{{ route('produk.store') }}" method="POST" enctype="multipart/form-data">
                                @csrf
                                <div class="row">
                                    <div class="col-6">
                                        <div class="form-group">
                                            <label for="jenis">Jenis</label>
                                            <select class="form-control form-control-sm" name="jenis">
                                                <option value="">Pilih jenis produk</option>
                                                <option value="Sapi">Sapi</option>
                                                <option value="Kambing">Kambing</option>
                                                <option value="Domba">Domba</option>
                                            </select>
                                        </div>
                                        <div class="form-group">
                                            <label for="type">Type</label>
                                            <select name="type" id="" class="form-control">
                                                <option value="">Pilih type produk</option>
                                                <option value="Type A">type A</option>
                                                <option value="Type B">type B</option>
                                                <option value="Type C">type C</option>
                                                <option value="Type D">type D</option>
                                            </select>
                                        </div>
                                        <div class="form-group">
                                            <label for="gender">Jenis Kelamin</label>
                                            <select name="gender" id="" class="form-control">
                                                <option value="">Pilih jenis kelamin</option>
                                                <option value="Jantan">Jantan</option>
                                                <option value="Betina">Betina</option>
                                            </select>
                                        </div>
                                        <div class="form-group">
                                            <label for="status">Status</label>
                                            <select name="status" id="" class="form-control">
                                                <option value="">Pilih Status</option>
                                                <option value="Tersedia">Tersedia</option>
                                                <option value="Kosong">Kosong</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-6">
                                        <div class="form-group">
                                            <label for="hight">Tinggi</label>
                                            <input type="text" name="hight" class="form-control">
                                        </div>
                                        <div class="form-group">
                                            <label for="wight">Berat</label>
                                            <input type="text" name="wight" class="form-control">
                                        </div>
                                        <div class="form-group">
                                            <label for="hargaBeli">Harga Beli</label>
                                            <input type="text" name="hargaBeli" class="form-control">
                                        </div>
                                        <div class="form-group">
                                            <label for="hargaJual">Harga Jual</label>
                                            <input type="text" name="hargaJual" class="form-control">
                                        </div>
                                        <div class="form-group">
                                            <h6>Upload Image</h6>
                                            <div class="controls">
                                                <input type="file" name="imageName" class="form-control" id="imageName">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <div class="controls">
                                                <img id="showImage" src="{{ url('uploads/no_image.jpg') }}"
                                                    style="width: 100px; width: 100px; border: 1px solid #000000;">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <br>
                                <button type="submit" class="btn btn-primary">Create</button>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script type="text/javascript">
        $(document).ready(function() {
            $('#imageName').change(function(e) {
                var reader = new FileReader();
                reader.onload = function(e) {
                    $('#showImage').attr('src', e.target.result);
                }
                reader.readAsDataURL(e.target.files['0']);
            });
        });
    </script>

@endsection

resources/views/backand/product/index.blade.php
@extends('layouts.master')

@section('title')
    RSUD Anugrah Sehat Afiat
@endsection()

@section('title-content')
    Data Pasien
@endsection()

@section('content')
    <!-- Page Heading -->
    <h1 class="h3 mb-3 text-gray-800">@yield('title-content')</h1>
    <div class="d-sm-flex align-items-center mb-2">
        <a href="{{ route('produk.create') }}"
            class="mr-3 d-none d-sm-inline-block btn btn-sm btn-outline-danger shadow-sm"><i
                class="fas fa-plus fa-sm text-white-50"></i> Pasien baru</a>
        <a href="{{ route('produk.create') }}" class="d-none d-sm-inline-block btn btn-sm btn-outline-primary shadow-sm"><i
                class="fas fa-plus fa-sm text-white-50"></i> Pasien lama</a>
    </div>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            {{-- <h6 class="m-0 font-weight-bold text-primary">Data Product</h6> --}}
        </div>
        <div class="card-body">
            @if ($message = Session::get('success'))
                <div class="alert alert-success alert-block">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    <strong>{{ $message }}</strong>
                </div>
            @endif
            @if (count($errors) > 0)
                <div class="alert alert-danger">
                    <strong>Whoops!</strong> There were some problems with your input.
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>id</th>
                            <th>jenis</th>
                            <th>type</th>
                            <th>berat</th>
                            <th>tinggi</th>
                            <th>gender</th>
                            <th>Harga</th>
                            <th>aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($produks as $key => $produk)
                            <tr>
                                <td>{{ $key + 1 }}</td>
                                <td>{{ $produk->jenis }}</td>
                                <td>{{ $produk->type }}</td>
                                <td>{{ $produk->wight }} kg</td>
                                <td>{{ $produk->hight }} cm</td>
                                <td>{{ $produk->gender }}</td>
                                <td>Rp. {{ number_format($produk->hargaJual) }}</td>
                                <td>
                                    <a href="{{ route('produk.edit', $produk->id) }}" class="btn btn-primary btn-sm"><i
                                            class="fas fa-pencil-alt"></i></a>
                                    <a href="{{ route('produk.show', $produk->id) }}"
                                        class="btn btn-sm btn-primary rounded-0"><i class="fas fa-eye"></i></a>
                                    <a href="{{ route('produk.destroy', $produk->id) }}"
                                        onclick="return confirm('Apakah anda yakin untuk menghapus data ini?')"
                                        class="btn btn-sm btn-danger rounded-0"><i class="fa fa-trash"></i></a>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection()

resources/views/backand/product/show.blade.php
@extends('layouts.master')

@section('title')
Jarvis Farm
@endsection

@section('title-content')
Farm
@endsection

@section('content')
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<div class="container">
    <div class="col-md-12">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <h1 class="h1 pb-4 py-3">Data Produk</h1>
            <div class="card mt-2">
                <div class="card-header">{{ __('Data Produk') }}</div>
                <div class="card-body">
                    @if ($message = Session::get('success'))
            <div class="alert alert-success alert-block">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <strong>{{ $message }}</strong>
            </div>
            @endif
            @if (count($errors) > 0)
            <div class="alert alert-danger">
                <strong>Whoops!</strong> There were some problems with your input.
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif
                    <form action="{{route('produk.update', $produks->id)}}" method="POST" enctype="multipart/form-data">
                        @csrf
                        @isset($produks)
                            {{ method_field('PATCH') }}
                        @endisset
                        <div class="row">
                        <div class="col-6">
                        <div class="form-group">
                        <label for="jenis">Jenis</label>
                        <select class="form-control form-control-sm" name="jenis">
                            <option selected="">{{ $produks->jenis }}</option>
                            <option value="Sapi">Sapi</option>
                            <option value="Kambing">Kambing</option>
                            <option value="Domba">Domba</option>
                        </select>
                        </div>
                        <div class="form-group">
                            <label for="type">Type</label>
                            <select name="type" id="" class="form-control">
                                <option selected="" >{{ $produks->type }}</option>
                                <option value="Type A">type A</option>
                                <option value="Type B">type B</option>
                                <option value="Type C">type C</option>
                                <option value="Type D">type D</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="gender">Jenis Kelamin</label>
                            <select name="gender" id="" class="form-control">
                                <option selected="" >{{ $produks->gender }}</option>
                                <option value="Jantan">Jantan</option>
                                <option value="Betina">Betina</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="status">Status</label>
                            <select name="status" id="" class="form-control" value="{{old('status', $produks->status ?? '')}}">
                                <option value="" >Pilih Status</option>
                                <option value="Tersedia">Tersedia</option>
                                <option value="Kosong">Kosong</option>
                            </select>
                        </div>
                    </div>
                        <div class="col-6">
                        <div class="form-group">
                            <label for="hight">Tinggi</label>
                            <input type="text" name="hight" class="form-control" value="{{ old('hight', $produks->hight ?? '') }}">
                        </div>
                        <div class="form-group">
                            <label for="wight">Berat</label>
                            <input type="text" name="wight" class="form-control" value="{{ old('wight', $produks->wight ?? '') }}">
                        </div>
                        <div class="form-group">
                            <label for="hargaBeli">Harga Beli</label>
                            <input type="text" name="hargaBeli" class="form-control" value="{{ old('hargaBeli', $produks->hargaBeli ?? '') }}">
                        </div>
                        <div class="form-group">
                            <label for="hargaJual">Harga Jual</label>
                            <input type="text" name="hargaJual" class="form-control" value="{{ old('hargaJual', $produks->hargaJual ?? '') }}">
                        </div>
                        <div class="form-group">
                            <h6>Upload Image</h6>
                            <div class="controls">
                            <input type="file" name="imageName" class="form-control" id="imageName" >
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="controls">
                                <img id="showImage" src="{{ (!empty($produks->imageName)) ? url('uploads/'.$produks->imageName):url('uploads/no_image.jpg') }}" style="width: 100px; width: 100px; border: 1px solid #000000;"> 
                            </div>
                         </div>
                    </div>
                </div>
                <br>
                    <a href="{{ route('produk.index') }}" type="button" class="btn btn-primary">Back</a>
                    
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

<script type="text/javascript">
    $(document).ready(function(){
        $('#imageName').change(function(e){
            var reader = new FileReader();
            reader.onload = function(e){
                $('#showImage').attr('src',e.target.result);
            }
            reader.readAsDataURL(e.target.files['0']);
        });
    });
</script>

@endsection

resources/views/backand/product/update.blade.php
@extends('layouts.master')

@section('title')
    Jarvis Farm
@endsection

@section('title-content')
    Farm
@endsection

@section('content')
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <div class="container">
        <div class="col-md-12">
            <div class="row justify-content-center">
                <div class="col-md-12">
                    <h1 class="h1 pb-4 py-3">Ubah Data Produk</h1>
                    <div class="card mt-2">
                        <div class="card-header">{{ __('Data Produk') }}</div>
                        <div class="card-body">
                            @if ($message = Session::get('success'))
                                <div class="alert alert-success alert-block">
                                    <button type="button" class="close" data-dismiss="alert">×</button>
                                    <strong>{{ $message }}</strong>
                                </div>
                            @endif
                            @if (count($errors) > 0)
                                <div class="alert alert-danger">
                                    <strong>Whoops!</strong> There were some problems with your input.
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif
                            <form action="{{ route('produk.update', $produks->id) }}" method="POST"
                                enctype="multipart/form-data">
                                @csrf
                                @isset($produks)
                                    {{ method_field('PATCH') }}
                                @endisset
                                <div class="row">
                                    <div class="col-6">
                                        <div class="form-group">
                                            <label for="jenis">Jenis</label>
                                            <select class="form-control form-control-sm" name="jenis">
                                                <option selected="">{{ $produks->jenis }}</option>
                                                <option value="Sapi">Sapi</option>
                                                <option value="Kambing">Kambing</option>
                                                <option value="Domba">Domba</option>
                                            </select>
                                        </div>
                                        <div class="form-group">
                                            <label for="type">Type</label>
                                            <select name="type" id="" class="form-control">
                                                <option selected="">{{ $produks->type }}</option>
                                                <option value="Type A">type A</option>
                                                <option value="Type B">type B</option>
                                                <option value="Type C">type C</option>
                                                <option value="Type D">type D</option>
                                            </select>
                                        </div>
                                        <div class="form-group">
                                            <label for="gender">Jenis Kelamin</label>
                                            <select name="gender" id="" class="form-control">
                                                <option selected="">{{ $produks->gender }}</option>
                                                <option value="Jantan">Jantan</option>
                                                <option value="Betina">Betina</option>
                                            </select>
                                        </div>
                                        <div class="form-group">
                                            <label for="status">Status</label>
                                            <select name="status" id="" class="form-control">
                                                <option selected>{{ $produks->status }}</option>
                                                <option value="Tersedia">Tersedia</option>
                                                <option value="Kosong">Kosong</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-6">
                                        <div class="form-group">
                                            <label for="hight">Tinggi</label>
                                            <input type="text" name="hight" class="form-control"
                                                value="{{ old('hight', $produks->hight ?? '') }}">
                                        </div>
                                        <div class="form-group">
                                            <label for="wight">Berat</label>
                                            <input type="text" name="wight" class="form-control"
                                                value="{{ old('wight', $produks->wight ?? '') }}">
                                        </div>
                                        <div class="form-group">
                                            <label for="hargaBeli">Harga Beli</label>
                                            <input type='text' name="hargaBeli" class="form-control"
                                                value="{{ old('hargaBeli', $produks->hargaBeli ?? '') }}">
                                        </div>
                                        <div class="form-group">
                                            <label for="hargaJual">Harga Jual</label>
                                            <input type="text" name="hargaJual" class="form-control"
                                                value="{{ old('hargaJual', $produks->hargaJual ?? '') }}">
                                        </div>
                                        <div class="form-group">
                                            <h6>Upload Image</h6>
                                            <div class="controls">
                                                <input type="file" name="imageName" class="form-control" id="imageName">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <div class="controls">
                                                <img id="showImage"
                                                    src="{{ !empty($produks->imageName) ? url('uploads/' . $produks->imageName) : url('uploads/no_image.jpg') }}"
                                                    style="width: 100px; width: 100px; border: 1px solid #000000;">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <br>
                                <button type="submit" class="btn btn-primary">Update</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script type="text/javascript">
        $(document).ready(function() {
            $('#imageName').change(function(e) {
                var reader = new FileReader();
                reader.onload = function(e) {
                    $('#showImage').attr('src', e.target.result);
                }
                reader.readAsDataURL(e.target.files['0']);
            });
        });
    </script>

@endsection