routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProdukController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\UserController;
use App\Models\User;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', [ProdukController::class, 'dataProduk']);


Route::prefix('admin')->namespace('Admin')->group(static function () {
        Route::resource('produk', 'ProductController');
        Route::resource('user', 'UserController');
});

Route::get('/delete/{id}', [UserController::class, 'destroy'])->name('userDelete');
Route::get('/delete/[id]', [ProductController::class, 'delete'])->name('delete');

// Route::get('user', [UserController::class, 'user']);
Route::get('formproduk', 'HomeController@formproduk')->name('formproduk');
Route::get('daftarbarang', [ProdukController::class, 'daftarBarang'])->name('daftarBarang');

// Route::get('depan',[ProdukController::class,'dataProduk']);
Route::POST('formproduk', [ProdukController::class, 'store']);

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

// Route::prefix('user')->group(function () {
//     Route::resource('produk', 'ProdukController');
// });

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'role',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;

class UserController extends Controller

{
    public function index()
    {
        $data['users'] = User::all();
        return view('backand.user.index', $data);
    }

    public function create()
    {
        return view('backand.user.create');
    }

    public function store(Request $request)
    {
        $user = new User;
        $user->name = $request->name;
        $user->email = $request->email;
        $user->password = bcrypt($request->password);
        $user->role = $request->role;
        //dd($user);
        $user->save();
        return view('backand.user.index');
    }

    public function show($id)
    {
        $users = User::findOrFail($id);
        return view('backand.user.show', compact([
            'users'
        ]));
    }

    public function edit($id)
    {
        $users = User::findOrFail($id);
        return view('backand.user.update', compact([
            'users'
        ]));
    }

    public function update(Request $request, $id)
    {
        $users = User::findOrFail($id);
        $users->name = $request->name;
        $users->email = $request->email;
        $users->role = $request->role;
        //dd($users);
        $users->save();

        return redirect()->route('user.index')->with('success', 'Data berhasil diupdate');
    }

    public function destroy($id)
    {
        $users = User::where('id', $id)->delete();
        //$users->delete();

        return redirect()->route('user.index')->with('success', 'Data berhasil dihapus');
    }
}

resources/views/backand/user/create.blade.php
@extends('layouts.master')

@section('title')
    Jarvis Farm
@endsection

@section('title-content')
    Farm
@endsection

@section('content')
    <div class="container">
        <div class="col-md-12">
            <div class="row justify-content-center">
                <div class="col-md-12">
                    <h1 class="h1 pb-4 py-3">Tambah User</h1>
                    <div class="card mt-2">
                        <div class="card-header">{{ __('Data User') }}</div>
                        <div class="card-body">
                            @if ($message = Session::get('success'))
                                <div class="alert alert-success alert-block">
                                    <button type="button" class="close" data-dismiss="alert">×</button>
                                    <strong>{{ $message }}</strong>
                                </div>
                            @endif
                            @if (count($errors) > 0)
                                <div class="alert alert-danger">
                                    <strong>Whoops!</strong> There were some problems with your input.
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif
                            <form action="{{ route('user.store') }}" method="POST" enctype="multipart/form-data">
                                @csrf
                                <div class="row">
                                    <div class="col-6">
                                        <div class="form-group">
                                            <label for="name">Name</label>
                                            <input type="text" name="name" class="form-control">
                                        </div>
                                        <div class="form-group">
                                            <label for="email">Email</label>
                                            <input type="email" name="email" class="form-control">
                                        </div>
                                    </div>
                                    <div class="col-6">
                                        <div class="form-group">
                                            <label for="role">Role</label>
                                            <select class="form-control form-control-sm" name="role" id="role">
                                                <option value="">Pilih Role</option>
                                                <option value="admin">Admin</option>
                                                <option value="user">User</option>
                                            </select>
                                        </div>
                                        <div class="form-group">
                                            <label for="password">Password</label>
                                            <input type="password" name="password" class="form-control">
                                        </div>
                                    </div>
                                </div>
                                <br>
                                <button type="submit" class="btn btn-primary">Create</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/backand/user/index.blade.php
@extends('layouts.master')

@section('title')
    Jarvis Farm
@endsection()

@section('title-content')
    Farm
@endsection()

@section('content')
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">@yield('title-content')</h1>
        <a href="{{ route('user.create') }}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i
                class="fas fa-plus fa-sm text-white-50"></i> Add User</a>
    </div>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Data User</h6>
        </div>
        <div class="card-body">
            @if ($message = Session::get('success'))
                <div class="alert alert-success alert-block">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    <strong>{{ $message }}</strong>
                </div>
            @endif
            @if (count($errors) > 0)
                <div class="alert alert-danger">
                    <strong>Whoops!</strong> There were some problems with your input.
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Name</th>
                            <th>Role</th>
                            <th>Email</th>
                            <th>Created at</th>
                            {{-- <th>Update at</th> --}}
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($users as $key => $user)
                            <tr>
                                <td>{{ $key + 1 }}</td>
                                <td>{{ $user->name }}</td>
                                <td>{{ $user->role }}</td>
                                <td>{{ $user->email }}</td>
                                <td>{{ $user->created_at }}</td>
                                {{-- <td>{{ $user->updated_at }}</td> --}}
                                <td>
                                    <a href="{{ route('user.edit', $user->id) }}" class="btn btn-primary btn-sm"><i
                                            class="fas fa-pencil-alt"></i></a>
                                    <a href="{{ route('user.show', $user->id) }}"
                                        class="btn btn-sm btn-primary rounded-0"><i class="fas fa-eye"></i></a>
                                    <a href="{{ route('userDelete', $user->id) }}" class="btn btn-sm btn-danger rounded-0"
                                        onclick="return confirm('Apakah anda yakin untuk menghapus data ini?')"
                                        style=""><i class="fa fa-trash"></i></a>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection()

resources/views/backand/user/show.blade.php
@extends('layouts.master')

@section('title')
    Jarvis Farm
@endsection

@section('title-content')
    Farm
@endsection

@section('content')
    <div class="container">
        <div class="col-md-12">
            <div class="row justify-content-center">
                <div class="col-md-12">
                    <h1 class="h1 pb-4 py-3">Hello, {{ $users->name }}</h1>
                    <div class="card mt-2">
                        <div class="card-header">{{ __('Data User') }}</div>
                        <div class="card-body">
                            @if ($message = Session::get('success'))
                                <div class="alert alert-success alert-block">
                                    <button type="button" class="close" data-dismiss="alert">×</button>
                                    <strong>{{ $message }}</strong>
                                </div>
                            @endif
                            @if (count($errors) > 0)
                                <div class="alert alert-danger">
                                    <strong>Whoops!</strong> There were some problems with your input.
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif
                            <form action="{{ route('user.update', $users->id) }}" method="POST"
                                enctype="multipart/form-data">
                                @csrf
                                @isset($users)
                                    {{ method_field('PATCH') }}
                                @endisset
                                <div class="row">
                                    <div class="col-6">
                                        <div class="form-group">
                                            <label for="name">Name</label>
                                            <input type="text" name="name" class="form-control"
                                                value="{{ $users->name }}">
                                        </div>
                                        <div class="form-group">
                                            <label for="email">Email</label>
                                            <input type="text" name="email" class="form-control"
                                                value="{{ $users->email }}">
                                        </div>
                                    </div>
                                    <div class="col-6">
                                        <div class="form-group">
                                            <label for="role">Role</label>
                                            <select class="form-control form-control-sm" name="role" id="role">
                                                <option value="">{{ $users->role }}</option>
                                                <option value="admin">Admin</option>
                                                <option value="user">User</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <br>
                                <a href="{{ route('user.index') }}" type="submit" class="btn btn-primary">back</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/backand/user/update.blade.php
@extends('layouts.master')

@section('title')
    Jarvis Farm
@endsection

@section('title-content')
    Farm
@endsection

@section('content')
    <div class="container">
        <div class="col-md-12">
            <div class="row justify-content-center">
                <div class="col-md-12">
                    <h1 class="h1 pb-4 py-3">Update User</h1>
                    <div class="card mt-2">
                        <div class="card-header">{{ __('Data User') }}</div>
                        <div class="card-body">
                            @if ($message = Session::get('success'))
                                <div class="alert alert-success alert-block">
                                    <button type="button" class="close" data-dismiss="alert">×</button>
                                    <strong>{{ $message }}</strong>
                                </div>
                            @endif
                            @if (count($errors) > 0)
                                <div class="alert alert-danger">
                                    <strong>Whoops!</strong> There were some problems with your input.
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif
                            <form action="{{ route('user.update', $users->id) }}" method="POST"
                                enctype="multipart/form-data">
                                @csrf
                                @isset($users)
                                    {{ method_field('PATCH') }}
                                @endisset
                                <div class="row">
                                    <div class="col-6">
                                        <div class="form-group">
                                            <label for="name">Name</label>
                                            <input type="text" name="name" class="form-control"
                                                value="{{ $users->name }}">
                                        </div>
                                        <div class="form-group">
                                            <label for="email">Email</label>
                                            <input type="text" name="email" class="form-control"
                                                value="{{ $users->email }}">
                                        </div>
                                    </div>
                                    <div class="col-6">
                                        <div class="form-group">
                                            <label for="role">Role</label>
                                            <select class="form-control form-control-sm" name="role" id="role">
                                                <option value="">{{ $users->role }}</option>
                                                <option value="admin">Admin</option>
                                                <option value="user">User</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <br>
                                <button type="submit" class="btn btn-primary">Update</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection